---
title: "classifiers"
author: "Vishwali"
date: "5/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(tidyverse)
```

```{r data_prep}
df.mob <- read_csv("https://raw.githubusercontent.com/mp5782/2338-Project/main/data/mobility_class.csv")
mob_smp <- floor(0.75 * nrow(df.mob))
df.case <- read_csv("https://raw.githubusercontent.com/mp5782/2338-Project/main/data/infection_class.csv")
case_smp <- floor(0.75 * nrow(df.case))

## mobility data split
set.seed(123)
train_ind1 <- sample(seq_len(nrow(df.mob)), size = mob_smp)
mobtrain <- df.mob[train_ind1, ]
mobtest <- df.mob[-train_ind1, ]
## case data split
set.seed(123)
train_ind2 <- sample(seq_len(nrow(df.case)), size = case_smp)
casetrain <- df.case[train_ind2, ]
casetest <- df.case[-train_ind2, ]
```

```{r lr_mob}
# Logistic Regression, Mobility
lr.mob <- glm(label_Mobility ~ confirmed_infections + rt + days0 + days1 + days2 +
                            days3 + days4 + days5 + days6, family = binomial, data = mobtrain)
summary(lr.mob)

# test the mobility logistic regression
predicted_probs<-predict(lr.mob,mobtest,type="response")
predicted<-predicted_probs>0.5
predicted<-as.numeric(predicted)
confusion_matrix <- table(mobtest$label_Mobility, predicted, dnn = c("Actual", "Predicted"))
confusion_matrix

total<-length(mobtest$label_Mobility) #get the count of all
accuracy<- (confusion_matrix[1,1]+confusion_matrix[2,2])/total
accuracy*100
```

```{r lda_mob}
#LDA, mobility
lda.mob <-lda(label_Mobility ~ confirmed_infections + rt + days0 + days1 + days2 +
                            days3 + days4 + days5 + days6,data=mobtrain)
summary(lda.mob)
lda_predicted <- predict(lda.mob,mobtest)
lda_label =lda_predicted$class
table(mobtest$label_Mobility,lda_label,dnn = c("Actual", "Predicted"))

#test of mobility LDA
accuracy_lda_test <- mean(lda_label==mobtest$label_Mobility)
accuracy_lda_test*100
```

```{r lr_case}
# logistic regresssion, infections
lr.case <- glm(label_confirmed_infections ~ Mobility + rt + days0 + days1 + days2 +
                            days3 + days4 + days5 + days6, family = binomial, data = casetrain)
summary(lr.case)

# test the  infection logistic regression
predicted_probs<-predict(lr.case,casetest,type="response")
predicted<-predicted_probs>0.5
predicted<-as.numeric(predicted)
confusion_matrix <- table(casetest$label_Mobility, predicted, dnn = c("Actual", "Predicted"))
confusion_matrix

total<-length(casetest$label_confirmed_infections) #get the count of all
accuracy<- (confusion_matrix[1,1]+confusion_matrix[2,2])/total
accuracy*100
```

```{r lda_case}
#LDA, infections
lda.case <-lda(label_confirmed_infections ~ Mobility + rt + days0 + days1 + days2 +
                            days3 + days4 + days5 + days6,data=casetrain)
summary(lda.case)
lda_predicted <- predict(lda.case,casetest)
lda_label =lda_predicted$class
table(casetest$label_confirmed_infections,lda_label,dnn = c("Actual", "Predicted"))

#test of infection  LDA
accuracy_lda_test <- mean(lda_label==casetest$label_confirmed_infections)
accuracy_lda_test*100
```
