---
title: "Final Project, Machine Learning in Public Health"
author: "Vishwali Mhasawade & Matthew Pathak"
date: "4/24/2021"
output:
  pdf_document:
    latex_engine: xelatex
---

# Introduction

At both national and subnational levels we will assess the impact of covid lockdown interventions (movement restrictions and household confinement) on several health outcomes (case growth rate, mortality rate, and mobility) in India. We are specifically looking for causal links between the interventions and the outcomes.

# Related Work



# Methods

1 Establish reliable causal inference via interrupted time series analysis. Discontinued regression allows for different intercepts and slopes to be generated by stratifying the data based on the implementation of an intervention. Significant differences between regressions spanning the same time period but segregated by the implementation of an intervention would imply an impact by that intervention. Identifying a consistent impact across all intervention phases lends support to the existence of a causal relationship between the interventions and the outcomes.

1 ML ALGO: classify based on binary criteria: "location has successfully implemented movement restrictions". Previously established causal relationship provides credibiilty for this prediction.

# Data and Experiment Setup

Data obtained from IHME, Johns Hopkins University, and [insert other regression discontinuity source].

# Results

## Causal Inference

[discuss results of regression discontinuity analysis]

## Classification

[discuss algo's performance re: discerning implementation of movement restrictions]

# References

1 Institute for Health Metrics and Evaluation (IHME). COVID-19 Mortality, Infection, Testing, Hospital Resource Use, and Social Distancing Projections. Seattle, United States of America: Institute for Health Metrics and Evaluation (IHME), University of Washington, 2020.
1 https://ds4ps.org/pe4ps-textbook/docs/p-020-time-series.html
1 Brodersen KH, Gallusser F, Koehler J, Remy N, Scott SL. Inferring causal impact using Bayesian structural time-series models. Annals of Applied Statistics, 2015, Vol. 9, No. 1, 247-274. http://research.google.com/pubs/pub41854.html
1 Feroze, Navid. "Forecasting the patterns of COVID-19 and causal impacts of lockdown in top five affected countries using Bayesian Structural Time Series Models." Chaos, Solitons & Fractals 140 (2020): 110196.
1 https://www.indiatvnews.com/news/india/lockdown-unlock-in-india-covid19-pandemic-guidelines-restrictions-2020-coronavirus-lockdown-series-674925
1 Bernal, James Lopez, Steven Cummins, and Antonio Gasparrini. "Interrupted time series regression for the evaluation of public health interventions: a tutorial." International journal of epidemiology 46.1 (2017): 348-355.